name = "TestRegistry"
uuid = "2a6cd22b-ecbb-a65f-de26-e512aa6fea8c"
repo = "https://github.com/staticfloat/TestRegistry.git"

description = """
Registry for testing purposes only.  Contains a few packages with artifacts for testing.
"""

[packages]
7876af07-990d-54b4-ab0e-23690620f79a = { name = "Example", path = "E/Example" }
1fd713ca-387f-5abc-8002-d8b8b1623b73 = { name = "A/Attr_jll", path = "A/Attr_jll" }
